
version: '3.8'
services:
  
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    expose:
      - "5000"  
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    links:
      - mongo 

  # Frontend (React)
  frontend:
    build: ./frontend
    ports:
      - "4300:80"

  # MongoDB
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - frontend
      - backend



volumes:
  mongo_data:
